- package.json
- yarn.lock
> feat(cli): add plugin-functions to devPlugins for implementation of list and display hooks

- src/hooks/envDisplay.ts
Ensure `data` exists before deleting the timestamp prop
[skip-validate-pr]
> fix: check if data exists

- src/commands/env/display.ts
- src/commands/env/list.ts
- yarn.lock
- Explicitly check if there are no environments and if so, show the appropriate error message
- Update to latest @oclif/core
@W-9902043@
> fix: show error message when no envs are available

- messages/display.md
- messages/list.md
- messages/open.md
- test/commands/env/open.test.ts
Updates help a bit to take into account compute environments. And edits some error messages.
@W-9676027@
> fix: minor edit of help and messages 

- .circleci/config.yml
- src/commands/env/list.ts
- src/commands/env/open.ts
Resolves failing `test-ts-update` tests
@W-10190107@
> chore: resolve test-ts-update failures

- .circleci/config.yml
- package.json
- src/commands/env/display.ts
- src/commands/env/list.ts
- yarn.lock
Removes `cli-ux` in favor of the ux methods on `SfCommand`
@W-10487585@
> feat: remove cli-ux

- messages/create.sandbox.md
- src/commands/env/create/sandbox.ts
Reviews the *md file associated with the "sf env create sandbox" command.  Also updates the command itself to take in new flag descriptions. 
@W-10878927@
> Review messages for "env create sandbox"

- messages/create_scratch.md
- src/commands/env/create/scratch.ts
Reviews/adds --help messages to 'sf env create scratch`
@W-10878935@
> Review messages for "sf env create scratch"

- messages/delete_sandbox.md
- messages/delete_scratch.md
Reviews messages for the "env delete scratch|sandbox" commands
@W-10878918@
> review messages for "env delete" commands

- messages/create_scratch.md
- messages/resume_scratch.md
- src/commands/env/create/scratch.ts
- src/commands/env/resume/scratch.ts
edits messages for sf env resume scratch and create scratch
@W-11013650@
> edit  messages for resume scratch

- package.json
- yarn.lock
Bump dependency versions
@W-0@
> fix: bump sf-plugins-core and others

- package.json
updates top-level description of "env" to match that in plugin-functions.  temporary fix to race condition about which description wins. 
@W-11195350@
> Update description to match the one in plugin-functions

- src/commands/env/resume/sandbox.ts
fixes assignment of prod org to class field
@W-0@
> fix: resume command does not store prod org in class property

- package.json
- test/commands/env/create/async-create-resume.nut.ts
- test/commands/env/create/sandbox.sandboxNut.ts
- test/commands/env/create/scratch.nut.ts
- test/commands/env/delete/scratch.nut.ts
- test/commands/env/display.nut.ts
- test/commands/env/list.nut.ts
- test/commands/env/open.nut.ts
- yarn.lock
Use latest cli-plugins-testkit
@W-11823417@
> chore: use latest testkit

- messages/create.sandbox.md
- messages/delete_sandbox.md
- messages/display.md
- messages/list.md
- messages/resume.sandbox.md
- messages/sandboxbase.md
fix messages problems discovered during QA of plugin-dev message audit. https://github.com/salesforcecli/plugin-dev/pull/209#issuecomment-1323949496
@W-12104524@
> fix: missing/unused message cleanup

- package.json
- schemas/env-create-scratch.json
- schemas/env-resume-scratch.json
- src/commands/env/create/sandbox.ts
- src/commands/env/list.ts
- src/commands/env/resume/sandbox.ts
- src/shared/orgHooks.ts
- src/shared/sandboxProgress.ts
- test/commands/env/create/createSandbox.test.ts
- test/tsconfig.json
- tsconfig.json
- yarn.lock
Uses sf-plugins-core v2 and oclif/core v2
@W-10791948@
> feat: update sf-plugins-core and oclif/core

- messages/display.md
Added description to example, better format. 
@W-12565029@
> fix: teeny messages fix

- src/commands/env/display.ts
- src/commands/env/open.ts
- test/commands/env/open.test.ts
remove deprecated methods to prepare for corev4
@W-13144170@
> refactor: remove sfdx error

- package.json
- src/commands/env/open.ts
- yarn.lock
Bump `open` to v9
[skip-validate-pr]
> fix: bump open

- package.json
- src/utils.ts
- yarn.lock
remove a completely unnecessary reference to a missing dep
https://github.com/forcedotcom/eslint-config-salesforce-typescript/actions/runs/7214346950/job/19656241442
> fix: remove ts-types wrapper
